FROM ubuntu:14.10
MAINTAINER Jonas Groß <gross.jonas@gmail.com>

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y ejabberd

EXPOSE 5222 5269 5280 4560 5280

RUN echo "#!/bin/bash" > /start.sh; \
  echo "service ejabberd start;" >> /start.sh; \
  echo "bash" >> /start.sh
RUN chmod +x /start.sh
ENTRYPOINT ["/start.sh"]
