FROM ubuntu

RUN \
  apt update

RUN \
  apt install -y apt-utils

RUN \
  apt install -y openjdk-8-jdk git npm

RUN \
  npm install --global bower

RUN \
  npm install --global gulp-cli

RUN \
  ln -s /usr/bin/nodejs /usr/local/bin/node

RUN \
  npm install --global yo

RUN \
  npm install generator-jhipster

RUN \
  apt install -y unzip

RUN \
  useradd -s /bin/bash -m -g sudo user
