FROM opensuse

RUN zypper install --no-confirm \
  java-1_8_0-openjdk-devel \
  git \
  npm

RUN npm install --global npm
RUN npm install --global bower yo gulp-cli generator-jhipster

RUN \
  groupadd user && \
  useradd user -s /bin/bash -m -g wheel && \
  chown -R user:user /home/user

RUN \
  mkdir /projects && \
  chown user:wheel /projects

RUN \
  zypper install --no-confirm \
    unzip \
    sudo

RUN \
  echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
  echo "Defaults        lecture = never" >> /etc/sudoers.d/privacy


ENV  MAVEN_VERSION=3.3.9

RUN \
  zypper in --no-confirm wget tar

RUN \
    cd /tmp && \
    wget -q "http://apache.ip-connect.vn.ua/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz"

RUN \
    cd /tmp && \
    tar -xzf "/tmp/apache-maven-$MAVEN_VERSION-bin.tar.gz"

RUN \
    mv "/tmp/apache-maven-$MAVEN_VERSION" "/usr/lib"

RUN \
    rm -rf "/tmp/"*

USER user

ENV JAVA_HOME=/etc/alternatives/java_sdk

ENV M2_HOME=/usr/lib/apache-maven-$MAVEN_VERSION

ENV PATH=${PATH}:${JAVA_HOME}/bin:${M2_HOME}/bin

WORKDIR /projects

CMD tail -f /dev/null
