FROM opensuse:42.1

RUN zypper install --no-confirm \
  java-1_8_0-openjdk-devel \
  git \
  npm

RUN npm install --global npm
RUN npm install --global bower yo gulp-cli generator-jhipster

RUN \
  groupadd user && \
  useradd user -s /bin/bash -m -g user && \
  chown -R user:user /home/user

RUN \
  echo "" >> /home/user/.bashrc && \
  echo "export JAVA_HOME=/etc/alternatives/java_sdk" >> /home/user/.bashrc

RUN \
  mkdir /projects && \
  chown user:user /projects

RUN \
  zypper install --no-confirm \
    unzip \
    sudo

RUN \
  echo "%user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
  echo "Defaults        lecture = never" >> /etc/sudoers.d/privacy

USER user

WORKDIR /projects

CMD tail -f /dev/null
