FROM codenvy/alpine_jdk8

RUN \
  apk upgrade --update && \

  apk add sudo && \
  apk add bash && \
  apk add unzip && \

  apk add openjdk8 && \
  apk add git && \
  apk add nodejs-lts && \

  npm install --global npm && \

  npm install --global bower && \
  npm install --global gulp-cli && \
  npm install --global yo && \

  npm install --global generator-jhipster && \

  adduser -s /bin/ash -G wheel -D user && \
  echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \

  mkdir /projects && \
  chown user:wheel /projects

ENV \
  MAVEN_VERSION=3.3.9

RUN \
  cd /tmp && \
  wget -q "http://apache.ip-connect.vn.ua/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz" && \
  tar -xzf "apache-maven-$MAVEN_VERSION-bin.tar.gz" && \
  mv "/tmp/apache-maven-$MAVEN_VERSION" "/usr/lib" && \
  rm -rf "/tmp/apache-maven-$MAVEN_VERSION"

USER user

ENV \
  M2_HOME=/usr/lib/apache-maven-$MAVEN_VERSION " && \
  JAVA_HOME=/usr/lib/jvm/default-jvm && \
  PATH=${PATH}:${JAVA_HOME}/bin:${M2_HOME}/bin"

WORKDIR /projects

CMD tail -f /dev/null
